### ISSUE TITLE
New redirect only shows top level nodes even when child nodes have domains assigned

### ISSUE THREAD

**Issue by D-Inventor** [Infocaster/UrlTracker#58]
Hi there,

We're having this exact issue in our Umbraco 8.12.1 setup where we have our site domains set on child nodes and not the top-level node so URL Tracker isn't working for us at all right now.

Is there any way to fix this issue in URL Tracker v4.1.132? We're stuck on our current version of U8 because of some breaking changes that will affect us in the later versions but we can't upgrade to a newer version of URL Tracker without upgrading Umbraco 8.

Any help would be much appreciated. 

Thanks,
Em

_Originally posted by @emilyps in https://github.com/Infocaster/UrlTracker/issues/53#issuecomment-1173349499_

**Comment by D-Inventor** [comment]
As mentioned in my previous response, I'll be porting the fixes from v9 and v10 to the v5 version and I'll lower the dependency version.

**Comment by emilybotha** [comment]
Thank you so much! Our team has spent quite some time trying to fix this using our own methods but I would much prefer continue using URL Tracker if possible as it worked brilliantly for us in U7. Sadly we didn't realise it wasn't working in our version of U8 until after we went to prod so we're without redirects at all for the moment. 

Once the dependency is lowered, our devs will test the stability with v8.12.1. Fingers crossed all goes well porting the U9 fix to v5.

Thanks again,
Em

**Comment by D-Inventor** [comment]
In [Version 5.0.2-beta0002](https://www.nuget.org/packages/UrlTracker/5.0.2-beta0002) I have reduced the Umbraco dependency version to 8.10.3 and higher, so you can already try it out.

It does not contain the bugfixes from v9 and v10 yet, so keep that in mind. The bugfixes should follow within 2 days from now.

**Comment by D-Inventor** [comment]
@emilyps I just released [version 5.1.0-beta0001](https://www.nuget.org/packages/UrlTracker/5.1.0-beta0001) which should contain all the bugfixes from v9 and v10. Do you have an opportunity to give it a try?

NOTE: Between v4 and v5, the name of the dll has changed! The old dlls are not automatically removed, which causes an exception on boot. Before building and before deployment, make sure that the old urltracker dll is removed.

**Comment by emilybotha** [comment]
Fantastic @D-Inventor - thank you for fixing this so quickly. I've let our team know and will come back to you once we've had a chance to test the latest beta.

**Comment by emilybotha** [comment]
Hey @D-Inventor,

We installed the latest beta and everything seems to be working now with regards to URL Tracker picking up that our domains are added on child pages and it's writing to the db correctly which is great news!! 

That said, redirects only started working once we moved our global site data folder (another custom doctype that doesn't contain a domain) down in the sort order of our websites in the pool. Guessing it was getting stuck because the first site in the list didn't have any domain?

One other smaller issue is to do with the root node ID list - because all of our child pages where the domains are added are all named the same (i.e. 'Welcome'), we can't differentiate between sites when creating a redirect unless we change the name of those pages. Not ideal but also not a showstopper. In the U7 version, it would automatically add the domain to the end of the page name in URL Tracker, e.g. 'Welcome (https://www.ourwebsite.com.au)'. Is there a way to get this working in v5?

Looking forward to hearing from you and many thanks again for all of your help.

Thanks,
Em

**Comment by D-Inventor** [comment]
Interesting discoveries. I can't imagine the sort order has any influence on matching, since I don't do anything with content directly (only through connected domains), but you never know. I'll see if I can reproduce this and come back when I find anything.
It would be very helpful for me if you're able to reproduce the issue and be able to share the logs on level 'Debug'. When logging is set to level 'Debug', the URL Tracker logs detailed steps in the matching process and you'll be able to see which parameters are used and how many matches are found.

It's a good idea to also include the URL of selected nodes, I understand the struggle, although I'm not 100% sure how that would work on content nodes with multiple domains. Should I just show the first domain?

I also intend to get rid of the root node setting on the long term ([see the last picture in the redirect redesign issue](https://github.com/Infocaster/UrlTracker/issues/35)), so maybe it's worth skipping this in favour of working on the redesign.

**Comment by emilybotha** [comment]
We're doing some further testing so I'll see if the team can reproduce with logging turned on and send you some further info on this part.  We couldn't quite work it out either but I don't think we had it set to level 'Debug' before. I'll come back to you on this once we've deployed the new version to our UAT pools and completed further testing.

Yep, I think the first domain in the list is fine but no worries if you'd prefer to work on the redesign and I can see whether this is something our devs could find a way to include on our side so we don't need to change the businesses' 'Welcome' page name.

**Comment by D-Inventor** [comment]
I've done a few tests, but haven't been able to reproduce the issue. I did notice after configuring some domains on deeper nodes that there was a url conflict with the topmost root node. Nevertheless, I was able to use the redirects without issue. Hopefully your team will be able to reproduce it and get some useful logs.

Also, if your team knows a solution for either of these issues, they're welcome to fork the URL Tracker repository and create a pull request. I'd be happy to review and integrate any contributions. More information about making contributions can be found in the [contribution guidelines](https://github.com/Infocaster/UrlTracker/blob/v10/develop/docs/CONTRIBUTING.md)

**Comment by marciscaupjonoks** [comment]
Hi @D-Inventor! Didn't want to open new issue, hope it's ok, since this might be related(child nodes with domains assigned). Is site and culture(*) should be blank in not founds table? Also when renaming content, new redirects show root node instead of child node that has domain, is that a bug?
I have simple setup root node -> child with domain (2 languages) and "HasDomainOnChildNode": true,
Umbraco 10.1.0 and UrlTracker 10.1.0

**Comment by D-Inventor** [comment]
Hi @marciscaupjonoks Thank you for reaching out! In version 10.x of the URL Tracker I've deliberately omitted the culture and site properties on the Not Found overview, but I'm minimizing development on the frontend as [we're soon planning a big overhaul of the frontend](https://github.com/Infocaster/UrlTracker/discussions/51). That's why the columns are still visible, despite lacking data.

Regarding your second point, I'm gonna see if I can reproduce the behaviour that you describe. I have no clearly defined requirements for handling content events, so there are certainly opportunities to improve. Do the redirects that the URL Tracker generates work? If the redirects don't work, then I'd like to invite you to [create a new issue](https://github.com/Infocaster/UrlTracker/issues/new/choose).

**Comment by marciscaupjonoks** [comment]
Thanks for quick reply!
I see. But then "create redirect" in not found table is not way to go then, since root node is grayed out there? Redirects work as expected when I create them from redirects section.

Just tested auto generated redirect and it does work even though it shows root node instead of child node with doman.

Edit: Actually manually added redirects don't seem to work with secondary culture ({domain}/sv)

**Comment by marciscaupjonoks** [comment]
Actually redirects don't seem to work with secondary culture ({domain}/sv)

**Comment by D-Inventor** [comment]
The feature to create redirects from the not found overview should still work, despite the root content dropdown being grayed out. The root content is determined automatically when you save the new redirect.

If a redirect doesn't work, I'd like to invite you to [create a new issue](https://github.com/Infocaster/UrlTracker/issues/new/choose) for it so I can help you without polluting this existing issue

**Comment by D-Inventor** [comment]
As we are no longer improving the package for Umbraco 8, except for security fixes, I'm going to close this issue.

New features and improvements are still being released for Umbraco 10 and 13
